# Site wide configuration

title: Projects
locale: en_US
description: Posts about my personal hobby projects
logo: 
search: true
# url: http://localhost:4000
production_url: http://vekkt0r.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments :
  provider : disqus

# Site owner
owner:
  name: Adam Engström
  avatar: bio-photo.jpg
  email: adreg@megalan.org
  github: #vekkt0r
  disqus-shortname: aeen
  google:
    plus: #username
    analytics: 'UA-58457222-1'
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
